import numpy as np
import gymnasium as gym
from gymnasium.spaces import Box, Discrete
from data_models.base_tower import BaseTower
from data_models.car_fcd_data import CarFcdData
from data_models.ng_ran_report import NGRANReport
from data_models.user_equipment import UserEquipment
from utils.fcd_parser import FcdParser
from utils.wave_utils import WaveUtils


class HandoverEnv(gym.Env):

    def __init__(
        self,
        base_towers: list[BaseTower],
        user_equipments: dict[int, UserEquipment],
        fcd_trace_file: str = "outputs/sumo/trace.xml",
    ):
        super().__init__()
        # UEs
        self.user_equipments = user_equipments
        # Agent
        self.agent = self.user_equipments[0]
        # All Base Towers
        self.base_towers = base_towers
        # action space: choosing 1 of 4 BS
        self.action_space = Discrete(4)
        # observation Space
        low = np.array([0] * 8 + [0] * 4)  # Min values for RSRP/RSRQ and One-Hot
        high = np.array([127] * 8 + [1] * 4)  # Max values
        self.observation_space = Box(low=low, high=high, dtype=np.int32)

        self.steps = 0
        self.fcd_data = FcdParser.parse_fcd_trace(trace_file=fcd_trace_file)

    def _top_4_towers(self, report: NGRANReport):
        rsrp_weight = 0.5
        rsrq_weight = 0.5

        scores: dict[int, float] = {}

        for bs in self.base_towers:
            bs_id = bs.id

            norm_rsrp = WaveUtils.normalize_rsrp_index(
                report.rsrp_values.get(bs_id, 0), bs.radio
            )
            norm_rsrq = WaveUtils.normalize_rsrq_index(
                report.rsrq_values.get(bs_id, 0), bs.radio
            )

            scores[bs_id] = (norm_rsrp * rsrp_weight) + (norm_rsrq * rsrq_weight)

        sorted_scores = sorted(scores.items(), key=lambda item: item[1], reverse=True)

        top_4_ids = [item[0] for item in sorted_scores[:4]]

        tower_lookup = {bs.id: bs for bs in self.base_towers}
        top_4_towers = [tower_lookup[t_id] for t_id in top_4_ids]

        return top_4_towers

    def _get_obs(self):
        if len(self.agent.generated_reports) < 1:
            return np.zeros(self.observation_space.shape, dtype=np.int32)
        # last report generated by the agent
        report: NGRANReport = self.agent.generated_reports[-1]

        # extract RSRP/RSRQ values from the 4 towers
        rsrp_list = [report.rsrp_values.get(bs.id, 0) for bs in self.base_towers]
        rsrq_list = [report.rsrq_values.get(bs.id, 0) for bs in self.base_towers]
        # connected tower index (garanteed to have a serving bs since generated reports >= 1)
        serving_position = self.base_towers.index(self.agent.serving_bs)
        serving_one_hot = [
            1 if i == serving_position else 0 for i in range(len(self.base_towers))
        ]
        # observation
        obs = np.concatenate([rsrp_list, rsrq_list, serving_one_hot], dtype=np.int32)
        return obs

    def step(self, action):
        target_bs = self.base_towers[action]
        handover_penalty = 15
        current_fcd_dict: dict[int, CarFcdData] = self.fcd_data[self.steps]
        if self.agent.id not in current_fcd_dict:
            # The car reached its destination, Episode terminated.
            obs = self._get_obs()
            return obs, 0.0, True, False, {"info": "Agent vehicle reached destination."}

        timestep = current_fcd_dict[self.agent.id].timestep
        old_tower = self.agent.serving_bs
        handover_executed = False
        # --- Execute Action ---
        if self.agent.serving_bs != target_bs:
            if self.agent.serving_bs is None:
                self.agent.connect_to_tower(bs=target_bs, timestep=timestep)
            else:
                # Trigger Handover
                self.agent.handover(target_bs, timestep=timestep)
                handover_executed = True  # Penalty to prevent ping-pongs

        new_tower = self.agent.serving_bs
        # Move cars
        if self.steps < len(self.fcd_data):
            fcds = self.fcd_data[self.steps].values()
            for fcd in fcds:
                car = self.user_equipments.get(fcd.id)
                if car:
                    # NOTE: DDQN Algorithm SHOULD NOT Execute the handover
                    car.move_to(fcd.latlng, timestep=fcd.timestep)

        # get agent report before/after moving
        report_before = self.agent.generated_reports[-2]
        report_after = self.agent.generated_reports[-1]
        # NOTE: RSRP and RSRQ are normalized. (0 to 1)
        # RSRP: /127 NR, /97 LTE
        # RSRQ 127 ,/34 LTE
        rsrp_before = WaveUtils.normalize_rsrp_index(
            rsrp_index=report_before.rsrp_values[self.agent.serving_bs.id],
            radio_type=old_tower.radio,
        )
        rsrp_after = WaveUtils.normalize_rsrp_index(
            rsrp_index=report_after.rsrp_values[self.agent.serving_bs.id],
            radio_type=new_tower.radio,
        )

        rsrq_before = WaveUtils.normalize_rsrq_index(
            rsrq_index=report_before.rsrq_values[self.agent.serving_bs.id],
            radio_type=old_tower.radio,
        )
        rsrq_after = WaveUtils.normalize_rsrq_index(
            rsrq_index=report_after.rsrq_values[self.agent.serving_bs.id],
            radio_type=new_tower.radio,
        )

        if handover_executed:
            reward = (
                (rsrp_after - rsrp_before)
                + (rsrq_after - rsrq_before)
                - handover_penalty
            )
        else:
            reward = (rsrp_before - rsrp_after) + (rsrq_before - rsrq_after)

        truncated = self.steps >= len(self.fcd_data)  # End of the SUMO trace
        terminated = False
        info = {}  # TODO: add info if needed in the future

        self.steps += 1
        obs = self._get_obs()
        return obs, float(reward), terminated, truncated, info

    def reset(self, seed=None, options=None):
        return super().reset(seed=seed, options=options)
